server.port: 8761
spring.application.name: spring-cloud-discovery
eureka:
  instance:
    hostname: host.docker.internal
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: eu-west-1
management:
  endpoints:
    web:
      exposure:
        include: health, info
    health:
      show-details: never
      probes.enabled: true